version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  express-api-1:
    build:
      context: ./express
      dockerfile: Dockerfile
    networks:
      - my_network

  express-api-2:
    build:
      context: ./express
      dockerfile: Dockerfile
    networks:
      - my_network
      
networks:
  my_network: