version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  webapp1:
    image: express-api
    networks:
      - my_network

  webapp2:
    image: express-api
    networks:
      - my_network

  webapp3:
    image: express-api
    networks:
      - my_network

networks:
  my_network:

